// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBpyb-GxcT03c4z5CIq1OlKa7zrIFnRI',
    appId: '1:489826002106:web:70d5189cc7090b98df0e83',
    messagingSenderId: '489826002106',
    projectId: 'sanaddb1',
    authDomain: 'sanaddb1.firebaseapp.com',
    storageBucket: 'sanaddb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNpuA5CzcH_djqjJ9vWoNtMGn6I0iudSE',
    appId: '1:489826002106:android:d15a451061bf6225df0e83',
    messagingSenderId: '489826002106',
    projectId: 'sanaddb1',
    storageBucket: 'sanaddb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2HwkcPvXRnIH-qNXHgnyeMu1eXT9Uzro',
    appId: '1:489826002106:ios:d8643778ee1c86e7df0e83',
    messagingSenderId: '489826002106',
    projectId: 'sanaddb1',
    storageBucket: 'sanaddb1.appspot.com',
    iosBundleId: 'com.example.sanadApp',
  );
  
}
